db: postgresql
passwd: '123456'
user_name: postgres
db_name: fuzz
host: 127.0.0.1
port: 7000

sqlsmith: ./sqlsmith
tmp_query: ./.dump-query
tmp_err: ./.err
output: querypool

capacity: 100

startup_cmd: "postgres -D /home/postgresql-10.23/install/data -p 7000 &"
# log_dir: "/home/planfuzzer/lab/"